"use client";

import { useSession } from "next-auth/react";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import Link from "next/link";
import Button from "@/components/ui/Button";
import { uploadJsonToIpfs } from "@/lib/ipfs";
import { writeIndexFromClient } from "@/lib/stellar";
import { apiFetch } from "@/lib/api";

/* Time range options */
const TIME_RANGES = [
  { value: "7d", label: "Last 7 days" },
  { value: "30d", label: "Last 30 days" },
  { value: "90d", label: "Last 90 days" },
  { value: "custom", label: "Custom range" },
] as const;

type TimeRange = (typeof TIME_RANGES)[number]["value"];

export default function BuyerRequestPage() {
  const { data: session, status } = useSession();
  const router = useRouter();

  const stellarAddress = (session?.user as { stellarAddress?: string })?.stellarAddress;

  /* Form fields */
  const [title, setTitle] = useState("");
  const [apiSourceUrl, setApiSourceUrl] = useState("");
  const [metrics, setMetrics] = useState<string[]>([]);
  const [metricInput, setMetricInput] = useState("");
  const [timeRange, setTimeRange] = useState<TimeRange>("30d");
  const [customStart, setCustomStart] = useState("");
  const [customEnd, setCustomEnd] = useState("");
  const [budget, setBudget] = useState<number>(50);
  const [batchSize, setBatchSize] = useState<number>(10);
  const [attestorUrl, setAttestorUrl] = useState("");
  const [deliveryPublicKey, setDeliveryPublicKey] = useState("");

  /* Submission state */
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<{
    skillId: string;
    ipfsHash: string;
    txHash: string;
    skillMd: string;
  } | null>(null);

  useEffect(() => {
    if (status === "unauthenticated") router.push("/login");
  }, [status, router]);

  /* Generate a random hex keypair placeholder */
  const handleGenerateKeypair = () => {
    const bytes = new Uint8Array(32);
    crypto.getRandomValues(bytes);
    const hex = Array.from(bytes)
      .map((b) => b.toString(16).padStart(2, "0"))
      .join("");
    setDeliveryPublicKey(hex);
  };

  /* Metric tag management */
  const addMetric = () => {
    const trimmed = metricInput.trim().toLowerCase();
    if (!trimmed || metrics.includes(trimmed)) {
      setMetricInput("");
      return;
    }
    setMetrics((prev) => [...prev, trimmed]);
    setMetricInput("");
  };

  const removeMetric = (m: string) => {
    setMetrics((prev) => prev.filter((x) => x !== m));
  };

  const handleMetricKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" || e.key === ",") {
      e.preventDefault();
      addMetric();
    }
  };

  /* Build skill.md content */
  const buildSkillMd = (skillId: string, ipfsHash: string) => {
    return [
      `# Data Request: ${title}`,
      "",
      `**Skill ID:** ${skillId}`,
      `**IPFS CID:** ${ipfsHash}`,
      `**Creator:** ${stellarAddress}`,
      `**Created:** ${new Date().toISOString()}`,
      "",
      "## Request Details",
      "",
      `- **API Source:** ${apiSourceUrl}`,
      `- **Metrics:** ${metrics.join(", ")}`,
      `- **Time Range:** ${timeRange === "custom" ? `${customStart} to ${customEnd}` : TIME_RANGES.find((t) => t.value === timeRange)?.label}`,
      `- **Budget:** ${budget} USDC`,
      `- **Batch Size:** ${batchSize} rows per delivery`,
      attestorUrl ? `- **Attestor URL:** ${attestorUrl}` : "",
      deliveryPublicKey ? `- **Delivery Public Key:** ${deliveryPublicKey.slice(0, 16)}...` : "",
      "",
      "## How it works",
      "",
      "1. This request is published to IPFS and indexed on Stellar testnet.",
      "2. Eligible providers see the request and can accept it.",
      "3. Providers fetch data from the API source and generate ZK-TLS proofs.",
      "4. Data is delivered in encrypted batches; escrow releases payment on verification.",
      "",
      "---",
      "Generated by PDE (Privacy-Preserving Data Economy)",
    ]
      .filter(Boolean)
      .join("\n");
  };

  /* Submit handler */
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);

    if (!title.trim()) {
      setError("Title is required.");
      return;
    }
    if (!apiSourceUrl.trim()) {
      setError("API Source URL is required.");
      return;
    }
    if (metrics.length === 0) {
      setError("Add at least one metric.");
      return;
    }
    if (budget <= 0) {
      setError("Budget must be greater than 0.");
      return;
    }
    if (!stellarAddress) {
      setError("Wallet not connected.");
      return;
    }

    setSubmitting(true);

    try {
      const skillId = crypto.randomUUID();

      /* Step 1: Build skill JSON */
      const skillJson = {
        id: skillId,
        title: title.trim(),
        dataSource: apiSourceUrl.trim(),
        metrics,
        timeRange,
        customStartDate: timeRange === "custom" ? customStart : undefined,
        customEndDate: timeRange === "custom" ? customEnd : undefined,
        totalBudget: budget,
        batchSize,
        attestorUrl: attestorUrl.trim() || undefined,
        deliveryPublicKey: deliveryPublicKey || undefined,
        creatorAddress: stellarAddress,
        status: "active",
        createdAt: new Date().toISOString(),
        policy: {
          maxProofAgeHours: 24,
          replayProtectionWindowHours: 24,
        },
      };

      /* Step 2: Upload to IPFS */
      const ipfsHash = await uploadJsonToIpfs(skillJson, {
        name: `skill-${Date.now()}.json`,
        keyvalues: { type: "skill", id: skillId.slice(0, 32) },
      });

      /* Step 3: Index on Stellar */
      const { hash: txHash } = await writeIndexFromClient(
        stellarAddress,
        "skill",
        skillId,
        ipfsHash
      );

      /* Step 4: Notify backend (fire-and-forget) */
      apiFetch("/api/notify/skill", {
        method: "POST",
        body: JSON.stringify({
          skillId,
          ipfsHash,
          txHash,
          stellarAddress,
          data: skillJson,
        }),
      }).catch((err) => console.warn("[buyer/request] Backend notify failed:", err));

      /* Step 5: Build skill.md content */
      const skillMd = buildSkillMd(skillId, ipfsHash);

      setResult({ skillId, ipfsHash, txHash, skillMd });

      /* Step 6: Redirect after delay */
      setTimeout(() => {
        router.push("/buyer/requests");
      }, 5000);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Something went wrong");
    } finally {
      setSubmitting(false);
    }
  };

  /* Download skill.md */
  const handleDownloadMd = () => {
    if (!result?.skillMd) return;
    const blob = new Blob([result.skillMd], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `skill-${result.skillId.slice(0, 8)}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  /* Loading */
  if (status === "loading") {
    return (
      <div className="mx-auto max-w-3xl px-4 py-12">
        <div className="animate-pulse space-y-4">
          <div className="h-8 w-60 rounded bg-slate-900" />
          <div className="h-96 rounded-xl bg-slate-900" />
        </div>
      </div>
    );
  }

  /* Success state */
  if (result) {
    return (
      <div className="mx-auto max-w-3xl px-4 py-10 space-y-6">
        <div className="flow-surface rounded-xl p-6 space-y-4">
          <div className="flex items-center gap-3">
            <span className="flex h-10 w-10 items-center justify-center rounded-full bg-emerald-500/15 border border-emerald-400/40">
              <svg className="h-5 w-5 text-emerald-300" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
              </svg>
            </span>
            <div>
              <h2 className="text-xl font-bold text-slate-100">Request Created</h2>
              <p className="text-sm text-slate-400">
                Your data request is live on Stellar testnet.
              </p>
            </div>
          </div>

          <div className="space-y-2 text-xs">
            <div className="flex justify-between rounded-md border border-slate-700 bg-slate-900/40 px-3 py-2">
              <span className="text-slate-500">Skill ID</span>
              <span className="font-mono text-slate-200">{result.skillId.slice(0, 16)}...</span>
            </div>
            <div className="flex justify-between rounded-md border border-slate-700 bg-slate-900/40 px-3 py-2">
              <span className="text-slate-500">IPFS CID</span>
              <span className="font-mono text-emerald-300">{result.ipfsHash.slice(0, 20)}...</span>
            </div>
            <div className="flex justify-between rounded-md border border-slate-700 bg-slate-900/40 px-3 py-2">
              <span className="text-slate-500">Stellar TX</span>
              <a
                href={`https://stellar.expert/explorer/testnet/tx/${result.txHash}`}
                target="_blank"
                rel="noopener noreferrer"
                className="font-mono text-cyan-300 hover:underline"
              >
                {result.txHash.slice(0, 16)}...
              </a>
            </div>
          </div>

          <div className="flex gap-2">
            <Button variant="outline" size="sm" onClick={handleDownloadMd}>
              Download skill.md
            </Button>
            <Link
              href="/buyer/requests"
              className="rounded-md border border-emerald-400/40 bg-emerald-500/15 px-3 py-1.5 text-sm font-medium text-emerald-200 hover:bg-emerald-500/20 transition-colors"
            >
              View All Requests
            </Link>
          </div>

          <p className="text-[10px] text-slate-600">
            Redirecting to your requests in 5 seconds...
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-3xl px-4 py-10 space-y-6">
      {/* Header */}
      <div>
        <Link
          href="/buyer/dashboard"
          className="text-xs text-slate-500 hover:text-slate-300 transition-colors"
        >
          &larr; Back to Dashboard
        </Link>
        <h1 className="mt-3 text-3xl font-bold text-slate-100">Create Data Request</h1>
        <p className="mt-2 text-sm text-slate-400">
          Define what data you need, set your budget, and publish to the network.
          Providers will deliver ZK-verified batches to your escrow.
        </p>
      </div>

      {/* Form */}
      <form onSubmit={handleSubmit} className="flow-surface rounded-xl divide-y divide-slate-800">
        {/* Title */}
        <div className="p-4 space-y-1.5">
          <label className="flow-label-sm">Title</label>
          <input
            type="text"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            placeholder="e.g. Fitbit Daily Activity Data"
            className="flow-input"
            required
          />
        </div>

        {/* API Source URL */}
        <div className="p-4 space-y-1.5">
          <label className="flow-label-sm">API Source URL</label>
          <input
            type="url"
            value={apiSourceUrl}
            onChange={(e) => setApiSourceUrl(e.target.value)}
            placeholder="https://api.fitbit.com/1/user/-/activities/"
            className="flow-input"
            required
          />
          <p className="text-[10px] text-slate-500">
            The web API endpoint providers will fetch data from via ZK-TLS.
          </p>
        </div>

        {/* Metrics */}
        <div className="p-4 space-y-1.5">
          <label className="flow-label-sm">Data Type / Metrics</label>
          <div className="flex gap-2">
            <input
              type="text"
              value={metricInput}
              onChange={(e) => setMetricInput(e.target.value)}
              onKeyDown={handleMetricKeyDown}
              placeholder="e.g. steps, distance, calories"
              className="flow-input flex-1"
            />
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={addMetric}
              disabled={!metricInput.trim()}
            >
              Add
            </Button>
          </div>
          {metrics.length > 0 && (
            <div className="flex flex-wrap gap-1.5 mt-2">
              {metrics.map((m) => (
                <span
                  key={m}
                  className="inline-flex items-center gap-1 rounded-full border border-emerald-500/30 bg-emerald-500/10 px-2 py-0.5 text-xs text-emerald-300"
                >
                  {m}
                  <button
                    type="button"
                    onClick={() => removeMetric(m)}
                    className="hover:text-red-400 transition-colors"
                  >
                    x
                  </button>
                </span>
              ))}
            </div>
          )}
          <p className="text-[10px] text-slate-500">
            Press Enter or comma to add. These define what data fields you expect.
          </p>
        </div>

        {/* Time Range */}
        <div className="p-4 space-y-1.5">
          <label className="flow-label-sm">Time Range</label>
          <select
            value={timeRange}
            onChange={(e) => setTimeRange(e.target.value as TimeRange)}
            className="flow-input"
          >
            {TIME_RANGES.map((t) => (
              <option key={t.value} value={t.value}>
                {t.label}
              </option>
            ))}
          </select>
          {timeRange === "custom" && (
            <div className="grid grid-cols-2 gap-3 mt-2">
              <div>
                <label className="text-[10px] text-slate-500">Start Date</label>
                <input
                  type="date"
                  value={customStart}
                  onChange={(e) => setCustomStart(e.target.value)}
                  className="flow-input"
                />
              </div>
              <div>
                <label className="text-[10px] text-slate-500">End Date</label>
                <input
                  type="date"
                  value={customEnd}
                  onChange={(e) => setCustomEnd(e.target.value)}
                  className="flow-input"
                />
              </div>
            </div>
          )}
        </div>

        {/* Budget */}
        <div className="p-4 space-y-1.5">
          <label className="flow-label-sm">Budget (USDC)</label>
          <input
            type="number"
            value={budget}
            onChange={(e) => setBudget(Number(e.target.value))}
            min={0.01}
            step={0.01}
            className="flow-input"
            required
          />
          <p className="text-[10px] text-slate-500">
            Total USDC to lock in escrow. Released to providers on verified delivery (70/20/10 split).
          </p>
        </div>

        {/* Batch Size */}
        <div className="p-4 space-y-1.5">
          <label className="flow-label-sm">Batch Size</label>
          <input
            type="number"
            value={batchSize}
            onChange={(e) => setBatchSize(Number(e.target.value))}
            min={1}
            max={1000}
            className="flow-input"
          />
          <p className="text-[10px] text-slate-500">
            Rows per delivery batch. Providers deliver data in batches of this size.
          </p>
        </div>

        {/* Attestor URL */}
        <div className="p-4 space-y-1.5">
          <label className="flow-label-sm">
            Attestor URL{" "}
            <span className="text-slate-600">(optional)</span>
          </label>
          <input
            type="url"
            value={attestorUrl}
            onChange={(e) => setAttestorUrl(e.target.value)}
            placeholder="http://localhost:8001"
            className="flow-input"
          />
          <p className="text-[10px] text-slate-500">
            Your own ZK-TLS attestor server (self-hosted attestor-core).
            Leave empty to use the platform default.
          </p>
        </div>

        {/* Delivery Public Key */}
        <div className="p-4 space-y-1.5">
          <label className="flow-label-sm">Delivery Public Key</label>
          <div className="flex gap-2">
            <input
              type="text"
              value={deliveryPublicKey}
              readOnly
              placeholder="Click 'Generate' to create a keypair"
              className="flow-input flex-1 font-mono text-xs"
            />
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={handleGenerateKeypair}
            >
              Generate New Keypair
            </Button>
          </div>
          <p className="text-[10px] text-slate-500">
            Providers encrypt the data payload with this key.
            Only you can decrypt the delivered data.
          </p>
        </div>

        {/* Error */}
        {error && (
          <div className="px-4 py-3">
            <div className="rounded-md border border-red-500/30 bg-red-500/5 px-3 py-2 text-xs text-red-300">
              {error}
            </div>
          </div>
        )}

        {/* Submit */}
        <div className="flex items-center justify-between p-4">
          <p className="text-[10px] text-slate-600">
            This will upload to IPFS, index on Stellar, and notify the network.
          </p>
          <Button
            type="submit"
            variant="primary"
            size="md"
            isLoading={submitting}
            disabled={submitting}
          >
            {submitting ? "Publishing..." : "Publish Request"}
          </Button>
        </div>
      </form>
    </div>
  );
}
